name: quanlyvlxd
description: "Ứng dụng quản lý và bán vật liệu xây dựng"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.1
  
  # Database (Offline)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Image Picker
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  path_provider: ^2.1.1
  
  # Charts
  fl_chart: ^0.66.0
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.12.0
  path: ^1.8.3
  
  # Firebase - Full Stack
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  firebase_remote_config: ^4.3.5
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.0+5
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  
  # Code generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    # Fonts will be loaded dynamically if available in assets/fonts/
    # To add fonts: Download Roboto-Regular.ttf and Roboto-Bold.ttf
    # Place them in assets/fonts/ and uncomment the fonts section below
    # - assets/fonts/

  # Fonts for PDF Unicode support (uncomment when fonts are added)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
